baseURL = 'https://rikuto13ten.github.io'
languageCode = 'ja-jp'
title = 'りくと-備忘録'
theme = "my-blog-theme"
# hugo.toml
ignoreFiles = ["themes/.*/content/.*"]
[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    hardWraps = true
    unsafe = false
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    style = 'rose-pine-moon'

[caches]
  [caches.images]
    dir = ':cacheDir/images'