:PROPERTIES:
:ID:       E36F6FC4-B5CA-4363-9D2C-5239F3D55A15
:END:
#+TITLE: emacs-describe-command-list
* Emacs Describe コマンド一覧
** パッケージ・テーマ関連
*** ~describe-package~
指定されたパッケージのドキュメントを表示。パッケージの情報、依存関係、インストール状況を確認する。

*** ~describe-theme~
現在のテーマまたは指定されたテーマの情報を表示。テーマの設定内容、フェイスの定義を確認する。

** テキスト・文字関連
*** ~describe-text-properties~
ポイント位置のテキストプロパティを表示。フェイス、フォント、その他のテキスト属性を確認する。

*** ~describe-char~
ポイント位置の文字のプロパティを表示（C-u C-x = と同等）。文字のコードポイント、フォント、フェイスなどを詳細表示する。

*** ~describe-char-fold-equivalences~
文字の折りたたみ等価性を表示。検索時の文字の同等性（ひらがな・カタカナなど）を確認する。

*** ~describe-syntax~
現在の構文テーブルの内容を表示。どの文字が開始区切り文字か、単語の一部かなどを確認する。

*** ~describe-categories~
文字カテゴリテーブルの内容を表示。文字の分類（ひらがな、カタカナ、漢字など）を確認する。

*** ~describe-character-set~
指定された文字セットの情報を表示。Unicode、ASCII、JIS などの文字セット詳細を確認する。

** フォント・表示関連
*** ~describe-font~
要求されたフォントと実際に使用されているフォントを表示。現在使用しているフォントの詳細情報を確認する。

*** ~describe-fontset~
指定されたフォントセットの情報を表示。フォントセット名を入力し、その文字範囲と割り当てられたフォントを表示する。多言語表示でのフォント設定を確認する。

*** ~describe-face~
フェイス（文字の表示属性）の説明を表示。フォント、色、装飾などの文字表示設定を確認する。

*** ~describe-current-display-table~
現在の表示テーブルの内容を表示。文字の表示方法の設定を確認する。

*** ~describe-icon~
指定されたアイコンの情報を表示。Emacsで使用されるアイコンの詳細を確認する。

** 言語・入力関連
*** ~describe-specified-language-support~
指定された言語のサポート状況を表示。言語環境の設定と対応状況を確認する。

*** ~describe-input-method~
入力メソッド method を説明。日本語入力など、特定の入力方法の設定を確認する。

*** ~describe-language-environment~
言語環境 language-env で使用される文字セット、コーディングシステム、入力メソッドの情報を表示。特定言語環境の設定を確認する。

*** ~describe-coding-system~
コーディングシステム coding を説明。文字エンコーディングの詳細設定を確認する。

*** ~describe-current-coding-system~
現在のバッファで使用されているコーディングシステムの詳細を表示。ファイルのエンコーディング設定を詳細確認する。

*** ~describe-current-coding-system-briefly~
現在使用中のコーディングシステムを表示。現在のファイルの文字エンコーディングを確認する。

** 関数・変数・シンボル関連
*** ~describe-function~
Lisp関数の完全なドキュメントを表示。コマンドもLisp関数なので、コマンド名も使用可能。関数の説明、引数、使用例を確認する。

*** ~describe-variable~
Lisp変数のドキュメントを表示。関数と同様だが変数用。変数の現在値、説明、カスタマイズ情報を確認する。

*** ~describe-symbol~
シンボルのドキュメントを表示。関数と変数とフェイスすべてに対応。一つのコマンドですべてのシンボルタイプを確認可能。

*** ~describe-command~
指定されたコマンドのドキュメントを表示。M-x で実行するコマンドの詳細を確認する。

** キーバインド関連
*** ~describe-key~
キーが実行するコマンドの名前と説明を表示。キーバインドの詳細な説明を確認する。

*** ~describe-key-briefly~
キーが実行するコマンドの名前を表示。キーバインドを簡潔に確認（詳細版は describe-key）。

*** ~describe-bindings~
現在有効なすべてのキーバインドをリスト表示：マイナーモード、メジャーモード、グローバルの順。現在のバッファで使用可能なすべてのキーバインドを確認する。

*** ~describe-personal-keybindings~
use-package などで設定したパーソナルキーバインドをすべて表示。自分で設定したキーバインドを一覧表示する。

*** ~describe-prefix-bindings~
プレフィックスキーに続くキーバインドを表示。C-x、C-c などの後に続くキーバインドを確認する。

*** ~describe-keymap~
指定されたキーマップの内容を表示。特定モードや状況でのキーバインドを確認する。

** モード関連
*** ~describe-mode~
現在のメジャーモードとマイナーモードのドキュメントを表示。現在有効なモードの機能とキーバインドを確認する。

*** ~describe-minor-mode~
指定されたマイナーモードの説明を表示。特定のマイナーモードの機能と設定を確認する。

*** ~describe-minor-mode-from-symbol~
シンボルから指定されたマイナーモードの説明を表示。マイナーモードの機能と設定を確認する。

*** ~describe-minor-mode-from-indicator~
モードライン上のインジケーターからマイナーモードを説明。モードライン表示からマイナーモードの詳細を確認する。

** その他・システム関連
*** ~describe-gnu-project~
GNU プロジェクトに関する情報を表示。GNU プロジェクトについての説明。

*** ~describe-copying~
GNU Emacs のコピー条件を表示。ライセンス情報（GPL）を確認する。

*** ~describe-no-warranty~
GNU Emacs の無保証に関する詳細情報を表示。保証に関する法的情報を確認する。

*** ~describe-distribution~
GNU Emacs の新しいバージョンの入手方法に関する情報を表示。Emacs の配布情報を確認する。

*** ~describe-buffer-case-table~
現在のバッファの大文字小文字変換テーブルを表示。大文字小文字の変換ルールを確認する。

*** ~describe-widget~
ポイント位置のウィジェットの説明を表示。カスタマイズ画面などのウィジェット情報を確認する。
