:PROPERTIES:
:ID:       3D4CFCF8-821A-45DB-9F6C-E52E5E0B8A74
:END:
#+TITLE: 読書感想文の書き方

* 感想が書けないのはなぜか
自分が感想を書くのが苦手な理由を書いてみる。
- そもそも感想文を書く経験が少ない
    経験がなければ書けるものも書けない
- なにを想ったのか分からない
  忘れている
- 感情を大切にできていない

** Hello
#+begin_quote
出来事→自分→伝える相手→それらを全部俯瞰して見る自分
#+end_quote
* ありのままに書く
#+begin_quote
文章のなかに生まれた矛盾は、
まだ心のなかで折り合いのついていない感情であり、
うまく言葉にできない要因になっている「ねじれ」の部分です。

[[https://note.com/kwhrbys_sk/n/ncf7f53bf6353][参考]]
#+end_quote

このうまく言葉にできない感情を、引用元筆者は *ねじれ* と呼んでいるらしい。
良い表現なので使おうと思う。

この *ねじれ* を言葉にすることこそが、自分らしさを出すパーツらしい。
つまり、綺麗に書こうとして、せっかくの感情に添削をすると反って良くないわけだ。

* 印象に残るシーン
自分の心に残るシーンについて書くというもの。
+ 刺さったセリフでも
+ 美しいと思った表現でも
そういったことについて書く。

なぜそのセリフが刺さったのか、どうして美しいと思ったのか、どんな感情になったのか。

* 感情を大切にする
重要なのはそのときの感情。
あらすじを解説する必要はない。

* 何を伝えたいのか
そもそも、感想によって何を伝えたいのかを明確にする。

1. 本のおもしろさを知ってほしいのか
2. 自分の意見を伝えたいのか
3. 他の人に本を読んでほしいのか
4. 感想を言葉にしたいのか

自分の場合 4 だと思う。

* 感情を言葉にする
なので、自分の感想を言葉にするということを目標にする。
感情は言葉に表わしにくい。
つまりは、感情を表わす言葉を知る必要がある。

* 実践だ
さしあたって、今回読んだ 「イヴたちの楽園 藤紫乃女学園の怪異譚」の感想を書いてみる。
まずは箇条書きで

- 弟がなにかと入れかわってしまった。
  一体何者？何が目的なのか
  どこに連れていかれた
- 一見幸せに見える友達も秘密を抱えている。
  まさか家族を殺しているとは
  感情を全て与えるほど彼女は壊れていた。
- この学園怪しすぎる
  卵は誰が、何の目的で保管されていたのか
- 天神の地下で何がおこったのか
  学園と繋がりがあるのかな
  言いようのない不安がある。
  このままとんでもないことが起こるのではないか

*** 清書
#+begin_verse
何者かと入れかわってしまった弟を捜す成瀬先輩と、怪異が見える主人公の物語。

私は怪異モノが好きだ。
怪異とは、所謂幽霊や、妖怪、魔物、神などを指す。
怪異は人間の味方ではない。
この物語においてもそれは例外ではない。

怪異は常識が通用しない。
私にはそれが恐しく感じる、と同時に魅力を感じる。
期待という言葉が正しいのかは分からないがそれに近いだろう。
現実には起こり得ない事象を引き起こすそれは、今迄見たことのない世界を見せてくれる。

小百合が孵化させた怪物は一体なんだったのか、感情を喰われるというのはどんな体験なのだろう。
きっと何も感じないのだろう、感じるための感情を食べられているのだから。
それが分かっていながら感情を食べさせた彼女が、一体どれほど追い詰められていたのかは想像に難くない。

自分が同じ状況になったとき、果たして卵に感情を与えられずにいられるのだろうかと思う。
人間というのは、自分が思っているよりもずっと脆いのだと感じる。
きっと誰にでも起こりうることなのだろう。
#+end_verse


